version: "2"
linters:
  default: all
  settings:
    gosec:
      excludes:
        - G306
        - G115
        - G404
    goconst:
      min-occurrences: 4
    gocritic:
      disabled-checks:
        - singleCaseSwitch
    cyclop:
      max-complexity: 30
    lll:
      line-length: 150
    maintidx:
      under: 15
    nestif:
      min-complexity: 10
    revive:
      rules:
        - name: var-naming
          arguments:
            - ["ID"]
    stylecheck:
      initialisms:
        [
          "ACL",
          "API",
          "ASCII",
          "CPU",
          "CSS",
          "DNS",
          "EOF",
          "GUID",
          "HTML",
          "HTTP",
          "HTTPS",
          "IP",
          "JSON",
          "QPS",
          "RAM",
          "RPC",
          "SLA",
          "SMTP",
          "SQL",
          "SSH",
          "TCP",
          "TLS",
          "TTL",
          "UDP",
          "UI",
          "GID",
          "UID",
          "UUID",
          "URI",
          "URL",
          "UTF8",
          "VM",
          "XML",
          "XMPP",
          "XSRF",
          "XSS",
          "SIP",
          "RTP",
          "AMQP",
          "DB",
          "TS",
        ]
  issues:
    max-issues-per-linter: 0
    exclude-rules:
      - path: 'example_test\.go'
        text: "rewrite if-else to switch statement"
      - path: '(.+)_test\.go'
        text: "Use of weak random number generator"
      - path: '(.+)_test\.go'
        linters:
          - lll
  disable:
    - wsl
    - varnamelen
    - wastedassign
    - testpackage
    - staticcheck
    - recvcheck
    - prealloc
    - paralleltest
    - nolintlint
    - nlreturn
    - musttag
    - mnd
    - makezero
    - gochecknoglobals
    - funlen
    - exhaustruct
    - exhaustive
    - gocritic
    - gocognit
    - errcheck
    - gochecknoinits
    - depguard
    - err113
    - dupword
    - dupl
